default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['PG_DATABASE_USERNAME'] %>
  password: <%= ENV['PG_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: flaredown_development

test:
  <<: *default
  database: flaredown_test

production:
  <<: *default
  host: <%= ENV['PG_DATABASE_HOST'] || 'localhost' %>
  database: <%= ENV['PG_DATABASE_NAME'] %>
