default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('PG_DATABASE_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('PG_DATABASE_PASSWORD') { '' } %>

development:
  <<: *default
  database: flaredown_development

test:
  <<: *default
  database: flaredown_test

production:
  <<: *default
  host: <%= ENV.fetch('PG_DATABASE_HOST') { 'localhost' } %>
  database: <%= ENV.fetch('PG_DATABASE_NAME') %>
  pool: <%= ENV.fetch('DB_POOL') { 30 } %>
