---
:verbose: false
:concurrency: 2

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

:pidfile: tmp/sidekiq.pid
:queues:
  - <%= ENV['RACK_ENV'] %>.default
  - <%= ENV['RACK_ENV'] %>.mailers
